spring.application.name=hotelhub

# Porta da aplicacao
server.port=8080

# Configuracoes do H2
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativar o console do H2 no navegador (acesse: http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# O Hibernate vai criar as tabelas com base nas nossas classes Java (Entities)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.org.springframework.jdbc.datasource.init=DEBUG
